### ISSUE TITLE
Failed while compiling

### ISSUE THREAD

**Issue by ftharyanto** [HandsomeAndy/GPU-comcot#1]
I got an error while compiling from source. I have nvcc and gfortran installed. My OS is Kubuntu 20.04.

here's the output of `nvcc --version`:

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Sun_Jul_28_19:07:16_PDT_2019
> Cuda compilation tools, release 10.1, V10.1.243

and here's the output of `gfortran --version`:

> GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

and here's the error I got when executing `make` command:

> gfortran -lstdc++ -O2 comcot.o initialization.o output.o deform.o mass.o moment.o boundaries.o all_grids.o hotstart.o landslide.o wavemaker.o dispersion.o type_module.o -L/usr/local/cuda-9.2/lib64 -lcudart GPUcomcot.o GPUMass_s.o GPUMoment_s.o GPUOpen_BD.o GPUOutput.o nvobj.o -o comcot
> /usr/bin/ld: GPUcomcot.o: in function `cuda_boot_':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xed): undefined reference to `cudaGetDeviceProperties'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xfb): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x102): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x3c1): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x3c8): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x416): undefined reference to `cudaMemcpy'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x424): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x42b): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x495): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x49c): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x4e9): undefined reference to `cudaMemcpy'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x4f7): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x4fe): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x559): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x560): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x5e1): undefined reference to `cudaCreateChannelDesc'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x6af): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x6b6): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x736): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x73d): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x94a): undefined reference to `cudaStreamCreate'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x958): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x95f): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUcomcot.o: in function `cuda_update_':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x9f1): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x9f8): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xa3c): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xa43): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xa9e): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xaa5): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xb24): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xb2b): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xbcf): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xbd6): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xc56): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xc5d): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUcomcot.o: in function `cudaMallocMNZH(unsigned long, unsigned long, float*, float*)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xe03): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xe0a): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xe6b): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xe72): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xf0a): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xf11): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xf72): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xf79): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xfd4): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0xfdb): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1036): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x103d): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1098): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x109f): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x10fa): undefined reference to `cudaMemset2D'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1108): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x110f): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x117b): undefined reference to `cudaMemcpy2D'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x118d): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1194): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1200): undefined reference to `cudaMemcpy2D'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1212): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1219): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUcomcot.o: in function `cudaMalloc2E(void**, void*, void*, unsigned long)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x128d): undefined reference to `cudaMalloc'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x129b): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x12a2): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x12eb): undefined reference to `cudaMemset'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x12fd): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1304): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x134a): undefined reference to `cudaMemcpy'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1358): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x135f): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x13b3): undefined reference to `cudaMemset'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x13c5): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x13cc): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x141a): undefined reference to `cudaMemcpy'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1428): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x142f): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUcomcot.o: in function `__cudaUnregisterBinaryUtil()':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1499): undefined reference to `__cudaUnregisterFatBinary'
> /usr/bin/ld: GPUcomcot.o: in function `__nv_init_managed_rt_with_module(void**)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x14b8): undefined reference to `__cudaInitModule'
> /usr/bin/ld: GPUcomcot.o: in function `__nv_cudaEntityRegisterCallback(void**)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1512): undefined reference to `__cudaRegisterVar'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1549): undefined reference to `__cudaRegisterTexture'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1580): undefined reference to `__cudaRegisterTexture'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x15b5): undefined reference to `__cudaRegisterVar'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x15ea): undefined reference to `__cudaRegisterVar'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x161f): undefined reference to `__cudaRegisterVar'
> /usr/bin/ld: tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1654): undefined reference to `__cudaRegisterVar'
> /usr/bin/ld: GPUcomcot.o: in function `cudaError cudaMalloc<float>(float**, unsigned long)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x16aa): undefined reference to `cudaMalloc'
> /usr/bin/ld: GPUcomcot.o: in function `cudaError cudaMemcpyToSymbol<unsigned int [4]>(unsigned int const (&) [4], void const*, unsigned long, unsigned long, cudaMemcpyKind)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x16e6): undefined reference to `cudaMemcpyToSymbol'
> /usr/bin/ld: GPUcomcot.o: in function `cudaError cudaBindTexture2D<float2, 2, (cudaTextureReadMode)0>(unsigned long*, texture<float2, 2, (cudaTextureReadMode)0> const&, void const*, cudaChannelFormatDesc const&, unsigned long, unsigned long, unsigned long)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1735): undefined reference to `cudaBindTexture2D'
> /usr/bin/ld: GPUcomcot.o: in function `cudaError cudaUnbindTexture<float2, 2, (cudaTextureReadMode)0>(texture<float2, 2, (cudaTextureReadMode)0> const&)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x1753): undefined reference to `cudaUnbindTexture'
> /usr/bin/ld: GPUcomcot.o: in function `cudaError cudaMemcpyToSymbol<float2*>(float2* const&, void const*, unsigned long, unsigned long, cudaMemcpyKind)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x178f): undefined reference to `cudaMemcpyToSymbol'
> /usr/bin/ld: GPUcomcot.o: in function `cudaError cudaMallocPitch<float2>(float2**, unsigned long*, unsigned long, unsigned long)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x17c1): undefined reference to `cudaMallocPitch'
> /usr/bin/ld: GPUcomcot.o: in function `cudaError cudaMemcpyToSymbol<unsigned long>(unsigned long const&, void const*, unsigned long, unsigned long, cudaMemcpyKind)':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text+0x17fd): undefined reference to `cudaMemcpyToSymbol'
> /usr/bin/ld: GPUcomcot.o: in function `cudaChannelFormatDesc cudaCreateChannelDesc<float2>()':
> tmpxft_00003c1a_00000000-5_GPUcomcot.cudafe1.cpp:(.text._Z21cudaCreateChannelDescI6float2E21cudaChannelFormatDescv[_Z21cudaCreateChannelDescI6float2E21cudaChannelFormatDescv]+0x45): undefined reference to `cudaCreateChannelDesc'
> /usr/bin/ld: GPUMass_s.o: in function `mass_launch_':
> tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0x6b): undefined reference to `__cudaPushCallConfiguration'
> /usr/bin/ld: tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0x94): undefined reference to `cudaDeviceSynchronize'
> /usr/bin/ld: tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0x99): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0xc2): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUMass_s.o: in function `__cudaUnregisterBinaryUtil()':
> tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0x135): undefined reference to `__cudaUnregisterFatBinary'
> /usr/bin/ld: GPUMass_s.o: in function `__nv_init_managed_rt_with_module(void**)':
> tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0x154): undefined reference to `__cudaInitModule'
> /usr/bin/ld: GPUMass_s.o: in function `__device_stub__Z19mass_kernel_pitchedPK6float2S1_PKf(float2 const*, float2 const*, float const*)':
> tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0x22b): undefined reference to `__cudaPopCallConfiguration'
> /usr/bin/ld: GPUMass_s.o: in function `__nv_cudaEntityRegisterCallback(void**)':
> tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0x364): undefined reference to `__cudaRegisterFunction'
> /usr/bin/ld: GPUMass_s.o: in function `cudaError cudaLaunchKernel<char>(char const*, dim3, dim3, void**, unsigned long, CUstream_st*)':
> tmpxft_00003c34_00000000-5_GPUMass_s.cudafe1.cpp:(.text+0x3e5): undefined reference to `cudaLaunchKernel'
> /usr/bin/ld: GPUMass_s.o:(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
> /usr/bin/ld: GPUMoment_s.o: in function `momt_launch_':
> tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x48): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x4f): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0xcf): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0xd6): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x13d): undefined reference to `__cudaPushCallConfiguration'
> /usr/bin/ld: tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x15f): undefined reference to `cudaDeviceSynchronize'
> /usr/bin/ld: tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x164): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x18d): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUMoment_s.o: in function `__cudaUnregisterBinaryUtil()':
> tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x200): undefined reference to `__cudaUnregisterFatBinary'
> /usr/bin/ld: GPUMoment_s.o: in function `__nv_init_managed_rt_with_module(void**)':
> tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x21f): undefined reference to `__cudaInitModule'
> /usr/bin/ld: GPUMoment_s.o: in function `__device_stub__Z16momts_kernel_texPKfS0_(float const*, float const*)':
> tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x2cf): undefined reference to `__cudaPopCallConfiguration'
> /usr/bin/ld: GPUMoment_s.o: in function `__nv_cudaEntityRegisterCallback(void**)':
> tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x400): undefined reference to `__cudaRegisterFunction'
> /usr/bin/ld: GPUMoment_s.o: in function `cudaError cudaUnbindTexture<float2, 2, (cudaTextureReadMode)0>(texture<float2, 2, (cudaTextureReadMode)0> const&)':
> tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x44b): undefined reference to `cudaUnbindTexture'
> /usr/bin/ld: GPUMoment_s.o: in function `cudaError cudaBindTexture2D<float2, 2, (cudaTextureReadMode)0>(unsigned long*, texture<float2, 2, (cudaTextureReadMode)0> const&, void const*, cudaChannelFormatDesc const&, unsigned long, unsigned long, unsigned long)':
> tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x49a): undefined reference to `cudaBindTexture2D'
> /usr/bin/ld: GPUMoment_s.o: in function `cudaError cudaLaunchKernel<char>(char const*, dim3, dim3, void**, unsigned long, CUstream_st*)':
> tmpxft_00003c4e_00000000-5_GPUMoment_s.cudafe1.cpp:(.text+0x4ee): undefined reference to `cudaLaunchKernel'
> /usr/bin/ld: GPUOpen_BD.o: in function `openbd_launch_':
> tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x5e): undefined reference to `__cudaPushCallConfiguration'
> /usr/bin/ld: tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0xa4): undefined reference to `__cudaPushCallConfiguration'
> /usr/bin/ld: tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0xea): undefined reference to `__cudaPushCallConfiguration'
> /usr/bin/ld: tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x130): undefined reference to `__cudaPushCallConfiguration'
> /usr/bin/ld: tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x143): undefined reference to `cudaDeviceSynchronize'
> /usr/bin/ld: tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x148): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x171): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUOpen_BD.o: in function `__cudaUnregisterBinaryUtil()':
> tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x1db): undefined reference to `__cudaUnregisterFatBinary'
> /usr/bin/ld: GPUOpen_BD.o: in function `__nv_init_managed_rt_with_module(void**)':
> tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x1fa): undefined reference to `__cudaInitModule'
> /usr/bin/ld: GPUOpen_BD.o: in function `__device_stub__Z17openbd_kernel_tex7bd_side(bd_side)':
> tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x283): undefined reference to `__cudaPopCallConfiguration'
> /usr/bin/ld: GPUOpen_BD.o: in function `__nv_cudaEntityRegisterCallback(void**)':
> tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x3a6): undefined reference to `__cudaRegisterFunction'
> /usr/bin/ld: GPUOpen_BD.o: in function `cudaError cudaLaunchKernel<char>(char const*, dim3, dim3, void**, unsigned long, CUstream_st*)':
> tmpxft_00003c68_00000000-5_GPUOpen_BD.cudafe1.cpp:(.text+0x427): undefined reference to `cudaLaunchKernel'
> /usr/bin/ld: GPUOutput.o: in function `maxamp_launch_':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x5f): undefined reference to `__cudaPushCallConfiguration'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x77): undefined reference to `cudaDeviceSynchronize'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x7c): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0xa5): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUOutput.o: in function `cuda_getz_':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x13d): undefined reference to `cudaMemcpy2D'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x14f): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x156): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUOutput.o: in function `cuda_getmn_':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x279): undefined reference to `cudaMemcpy2D'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x28b): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x292): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUOutput.o: in function `cuda_getzmax_':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x3de): undefined reference to `cudaMemcpy'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x3ec): undefined reference to `cudaGetLastError'
> /usr/bin/ld: tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x3f3): undefined reference to `cudaGetErrorString'
> /usr/bin/ld: GPUOutput.o: in function `__cudaUnregisterBinaryUtil()':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x45d): undefined reference to `__cudaUnregisterFatBinary'
> /usr/bin/ld: GPUOutput.o: in function `__nv_init_managed_rt_with_module(void**)':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x47c): undefined reference to `__cudaInitModule'
> /usr/bin/ld: GPUOutput.o: in function `__device_stub__Z27maximum_recorder_kernel_texPf(float*)':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x506): undefined reference to `__cudaPopCallConfiguration'
> /usr/bin/ld: GPUOutput.o: in function `__nv_cudaEntityRegisterCallback(void**)':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x62c): undefined reference to `__cudaRegisterFunction'
> /usr/bin/ld: GPUOutput.o: in function `cudaError cudaLaunchKernel<char>(char const*, dim3, dim3, void**, unsigned long, CUstream_st*)':
> tmpxft_00003c82_00000000-5_GPUOutput.cudafe1.cpp:(.text+0x6ad): undefined reference to `cudaLaunchKernel'
> /usr/bin/ld: nvobj.o: in function `__cudaUnregisterBinaryUtil':
> link.stub:(.text+0x13): undefined reference to `__cudaUnregisterFatBinary'
> /usr/bin/ld: nvobj.o: in function `__cudaRegisterLinkedBinary(__fatBinC_Wrapper_t const*, void (*)(void**), void*)':
> link.stub:(.text+0x25a): undefined reference to `__cudaRegisterFatBinary'
> /usr/bin/ld: link.stub:(.text+0x2c9): undefined reference to `__cudaRegisterFatBinaryEnd'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:33: comcot] Error 1

**Comment by AndybnACT** [comment]
It is a link issue. Please point `NVLIB` at the Makefile to your cuda library.
